### ISSUE TITLE
ignore-styles.js:45 Uncaught TypeError: Cannot read property '.css' of undefined

### ISSUE THREAD

**Issue by Itagiba** [bkonkle/ignore-styles#11]
I am using this hook for babel-register as the later broke my styling in my Webpack/React project in trying to interpret styles as JS.

I am using [material-ui](http://www.material-ui.com/#/) and more specially the drawer menu. However as soon as I add ignore-styles.js to my app, I get the following error:

`ignore-styles.js:45 Uncaught TypeError: Cannot read property '.css' of undefined`

And the drawer menu stops working. 

This is what it is pointing to in ignore-styles.js (45):

```
    oldHandlers[ext] = (void 0)[ext];
    (void 0)[ext] = handler;
  }
```

What does this mean exactly?

**Comment by Itagiba** [comment]
There is definitely a bug with this. I have now implemented this [ menu](http://negomi.github.io/react-burger-menu/)  and `ignore-styles` also prevents it from working, throwing the same error:

`ignore-styles.js:45 Uncaught TypeError: Cannot read property '.css' of undefined`

**Comment by bkonkle** [comment]
Hi! I'm taking a look this evening to see if I can reproduce. I'll let you know what I find.

**Comment by bkonkle** [comment]
The real code there is:

``` js
  for (const ext of extensions) {
    oldHandlers[ext] = require.extensions[ext]
    require.extensions[ext] = handler
  }
```

It looks like some part of your build tooling is replacing `require.extensions` with `(void 0)`.

**Comment by bkonkle** [comment]
Aha, this is something that Webpack does. In webpack, you'll want to use a plugin like this: https://www.npmjs.com/package/ignore-loader

I'll add a note to the README. Thanks!

**Comment by Itagiba** [comment]
Hey thanks, but it is not working for me.  I am still getting the error in my console:

`Uncaught TypeError: Cannot read property '.css' of undefined`

I have installed and added it to my webpack.config:

```
    // Extract SCSS
    { test: /\.scss$/,
      loader: ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader")
    },
    { test: /\.css$/,
      loader: 'ignore-loader'
    },
```

How are you reproducing this?
