### ISSUE TITLE
Cannot find module '!style!css?modules&camelCase!./test.css'

### ISSUE THREAD

**Issue by zackshen** [bkonkle/ignore-styles#17]
help!!! Cannot find module '!style!css?modules&camelCase!./test.css'

**Comment by bkonkle** [comment]
I think this is probably not recognizing it as a ".css" file because of the Webpack loaders. I probably won't have time to look into this until the weekend, so if anyone else can help it would be much appreciated. 👍

**Comment by zackshen** [comment]
@bkonkle thanks, i'v resolved this problem.  
because of babel compiler can not recognized `!style!css`,  so we need to precompile the source code then test them. i found a awesome plugin `mocha-webpack`

**Comment by bkonkle** [comment]
Awesome! I'm glad you got it resolved, and thanks for posting the solution here. 👍

**Comment by rulatir** [comment]
@zackshen Did you by chance devise a `mocha-webpack` based solution that works with PHPStorm's Mocha run configuration (including autocreated configurations via Ctrl+Shift+F10) and automates the prebuild step?

**Comment by zackshen** [comment]
@rulatir I'm so sorry i can't, I'm now working under tmux and vim, no any experience about phpstorm
