### ISSUE TITLE
Ingore anything!

### ISSUE THREAD

**Issue by jdart** [bkonkle/ignore-styles#3]
Hi Dev,

I was having issues with tests run by mocha failing because of things like `require('foo.png')`, this module helps me overcome that by ignoring those requires. You could add that to the docs.

Cheers!

**Comment by karlhorky** [comment]
+1 This would also be an interesting feature to me.

I guess a workaround for now is to ignore the files in webpack (or whatever other tool you're using that allows `require('foo.png')`) using something like [null-loader](https://github.com/webpack/null-loader).

**Comment by bkonkle** [comment]
What @jdart is referring to is the fact that this library can do that already. In fact, I'm using it exactly that way in my current project:

```
require.extensions['.png'] = (module, filename) => {
  module.exports = path.basename(filename)
}
```

This means that whenever I import a `.png` file, it returns the basename of the file. That's something I can easily test against.

Great suggestion to add it to the docs! This is definitely a more powerful tool than I realized at first. :grinning:

**Comment by karlhorky** [comment]
Ah, missed that scanning over this issue quickly, oops :stuck_out_tongue:

**Comment by bkonkle** [comment]
Scratch that - I wasn't paying close enough attention. My example above isn't using this library at all. :laughing: I'll come up with examples soon that demonstrate how to use _ignore-styles_  more broadly.

**Comment by karlhorky** [comment]
Yeah I guess if that's often a use case, maybe renaming the project would be something to consider... maybe `babel-register-ignore-hook` or something.

**Comment by dqisme** [comment]
How's 'anything' going 😉?

**Comment by bkonkle** [comment]
Hi! Thanks for the reminder! I just published version 2.0.0, which includes some common image extensions, and includes some extra documentation on how to customize the usage and handlers.

**Comment by dqisme** [comment]
@bkonkle gooooood job! it works to scss and images. i can remove the strange null-compiler

**Comment by bkonkle** [comment]
Awesome! I'm so glad it's working well for you! :+1:
