### ISSUE TITLE
Works perfect in local environment but fails on travis.ci

### ISSUE THREAD

**Issue by lxibarra** [bkonkle/ignore-styles#6]
Hello, im running my tests locally and it works perfectly but on travis ci fails.
i get the follwoing error:
error: Cannot find module './HandCards.scss'

and npm run test has the following:
mocha tools/testSetup.js --require ignore-styles  src/**/**.spec.js 

Any ideas?
https://travis-ci.org/lxibarra/one

**Comment by bkonkle** [comment]
I'm guessing that `ignore-styles` isn't getting installed in the Travis.CI environment. Make sure that your setup script is installing it somewhere so that it is available when mocha is run with the --require flag.

**Comment by lxibarra** [comment]
Hey i was able to make it work. The problem was when importing './HandCards.scss' it should be './handCards.scss' (lower case h)  weird thing it work perfectly in my local machine.

Thanks for the help.

**Comment by bkonkle** [comment]
I'm so glad you were able to get it working! 👍

**Comment by kjs3** [comment]
@lxibarra you're on a mac right? I'm assuming this was a case-insensitivity issue?

**Comment by lxibarra** [comment]
yeap it was
